language: generic

script:
        - git clone https://github.com/apache/ignite.git ${TRAVIS_BUILD_DIR}/ignite-src
        - cd ignite-src
        - mvn --quiet clean install -DskipTests -Prelease
        - IGNITE_BIN=`find . -name "apache-ignite*.zip" | head -1`
        - cd -
        - cp $IGNITE_BIN ./ignite.zip
        - pwd
